### ISSUE TITLE
SafeRealloc()

### ISSUE THREAD

**Issue by kusalananda** [NBISweden/MrBayes#13]
I've merged the `feature/utils_cleanup` branch with `develop` just now.

The `SafeRealloc()` function went in as it was (returning `tmp`, not `ptr`!).  Can you see any issues with how it is implemented now? I'm uneasy about returning NULL if the requested size is zero as this signals a failure to allocate memory.

We could just document it as the behaviour though.

Thoughts?

**Comment by ronquist** [comment]
This is not a huge thing. Returning NULL on failure is what we did before, so I would leave it that way. It is also close to the default behavior of realloc, see
[cppreference.com page on realloc](http://en.cppreference.com/w/c/memory/realloc):

> If there is not enough memory, the old memory block is not freed and null pointer is returned.
> If ptr is NULL, the behavior is the same as calling malloc(new_size).
> If new_size is zero, the behavior is implementation defined (null pointer may be returned (in which case the old memory block is not freed), or some non-null pointer may be returned that may not be used to access storage). 

Specifically, it appears that previous support for 0-size allocation or reallocation has been removed from the C language standard from version c11.

The current MrBayes code should always check for a NULL pointer return and raise an error when calling any of the memory allocation routines. I am fairly confident there is no place where reallocation or allocation with zero size will be attempted and should be ignored, so it really should not matter what is returned under those conditions. Having said this, however, I could add that I just encountered such a situation. But clearly you do not have a valid pointer to memory after you ask for a zero-size realloc, so you might as well free the memory and return a NULL pointer; then the caller can deal with the zero-size allocation situation if they want to. Returning a non-null pointer is really bad unless that pointer can be used as an argument to free. But then there is no way for the caller to know that an error occurred except by checking for a zero-size allocation anyway.

One might think that it would be better to always free the allocated memory before returning a NULL pointer, even when you are out of memory. However, there is one scenario when you do not want this to happen. This is when you want to test to see whether there is more memory left, and then adapt your behvaior accordingly. This does require a different idiom than the ptr = realloc( ptr, ...) idiom we use in MrBayes now. However, choosing between risking memory leaks when recovering from out-of-memory and leaving it open to use alternative idioms allowed by the standard realloc, I would prefer to stick to the standard realloc behaviour. 

So return NULL on zero-size allocation and free the memory accordingly. On other allocation errors, return a NULL pointer and do not free the allocated memory in the process. That is basically the original code if I remember correctly.

I will fix these things shortly in this branch myself, because I also wanted to correct the English in the out-of-memory message (Maxim's English is characteristic), and then we can close this issue I hope. I will print a separate message if zero-size allocation is attempted, and then assume that this will be captured before the call if it is supposed to pass silently.

**Comment by ronquist** [comment]
Added this as a pull request instead, from a separate branch patch/memory_allocation.

**Comment by kusalananda** [comment]
I'm resolving the conflicts and will merge to 'develop' when done.

**Comment by kusalananda** [comment]
Conflicts resolved, pull request merged,branch deleted. This closes this issue.
