### ISSUE TITLE
Cannot install mrbayes - invalid attribute for formula 'brewsci/bio/mrbayes': version (nil)

### ISSUE THREAD

**Issue by rmwade** [NBISweden/MrBayes#147]
I have used MrBayes hundreds of times with GUI systems, but am trying to use the command line version to be able to make some more specific specifications to the block. However, I cannot get Bayes to install. Please see print out copied below:

  Rachaels-MacBook-Pro-3:Library rachaelwade$ brew tap brewsci/bio
==> Tapping brewsci/bio
Cloning into '/usr/local/Library/Taps/brewsci/homebrew-bio'...
remote: Enumerating objects: 304, done.
remote: Counting objects: 100% (304/304), done.
remote: Compressing objects: 100% (302/302), done.
remote: Total 304 (delta 1), reused 51 (delta 0), pack-reused 0
Receiving objects: 100% (304/304), 216.49 KiB | 308.00 KiB/s, done.
Resolving deltas: 100% (1/1), done.
Tapped 286 formulae (324 files, 1.5M)
(base) Rachaels-MacBook-Pro-3:Library rachaelwade$     brew install mrbayes
Error: invalid attribute for formula 'brewsci/bio/mrbayes': version (nil)
Please report this bug:
    https://git.io/brew-troubleshooting

This seems like a simple issue, but because the bug should be reported, I thought I should.

I appreciate any help or advice you can provide, thank you!

Rachael

**Comment by rmwade** [comment]
I should also note that that link provided to report the bug is dead.

**Comment by andkaha** [comment]
I can unfortunately not reproduce your issue on macOS Catalina (macOS 10.15.2):

```
[desktop] % brew tap brewsci/bio
==> Tapping brewsci/bio
Cloning into '/usr/local/Homebrew/Library/Taps/brewsci/homebrew-bio'...
remote: Enumerating objects: 304, done.
remote: Counting objects: 100% (304/304), done.
remote: Compressing objects: 100% (302/302), done.
remote: Total 304 (delta 1), reused 50 (delta 0), pack-reused 0
Receiving objects: 100% (304/304), 216.48 KiB | 1.03 MiB/s, done.
Resolving deltas: 100% (1/1), done.
Tapped 286 formulae (325 files, 662KB).
```
```
[desktop] % brew install mrbayes
==> Installing mrbayes from brewsci/bio
==> Downloading https://linuxbrew.bintray.com/bottles-bio/mrbayes-3.2.7.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/55/55f858faa19f1073cc030c19be1feb1cc154e6baaf3c8905f0953ba
######################################################################## 100.0%
==> Pouring mrbayes-3.2.7.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/mrbayes/3.2.7: 22 files, 7MB
```

**Comment by andkaha** [comment]
The `https://git.io/brew-troubleshooting` link that you see, and which indeed does not seem to be functioning, is not ours. It's a link reported by Homebrew.

The fact that it is not working makes me wonder whether you have _very old_ Homebrew installation on your system.

Could you try again after doing `brew upgrade`?

**Comment by rmwade** [comment]
Hi Andreas,

Thank you for your help! Unfortunately upgrading homebrew did not help, as
it seems homebrew doesn't play nice with Catalina, how did you get around
this? Please see the error below:

(base) Rachaels-MacBook-Pro-3:~ rachaelwade$ brew upgrade

Warning: You are using OS X 10.15.

We do not provide support for this pre-release version.

You may encounter build failures or other breakages.

(base) Rachaels-MacBook-Pro-3:~ rachaelwade$ brew install mrbayes

Error: invalid attribute for formula 'brewsci/bio/mrbayes': version (nil)

*Please report this bug:*

    *https://git.io/brew-troubleshooting
<https://git.io/brew-troubleshooting>*

/usr/local/Library/Homebrew/formula.rb:206:in `validate_attributes!'

/usr/local/Library/Homebrew/formula.rb:164:in `initialize'

/usr/local/Library/Homebrew/formulary.rb:71:in `new'

/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'

/usr/local/Library/Homebrew/formulary.rb:206:in `factory'

/usr/local/Library/Homebrew/formulary.rb:351:in `find_with_priority'

/usr/local/Library/Homebrew/extend/ARGV.rb:20:in `block in formulae'

/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'

/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'

/usr/local/Library/Homebrew/cmd/install.rb:44:in `install'

/usr/local/Library/brew.rb:143:in `<main>'

(base) Rachaels-MacBook-Pro-3:~ rachaelwade$

I also tried to update homebrew using brew update, but then got this error:

(base) Rachaels-MacBook-Pro-3:~ rachaelwade$ brew update

Error: The /usr/local directory is not writable.

Even if this directory was writable when you installed Homebrew, other

software may change permissions on this directory. Some versions of the

"InstantOn" component of Airfoil are known to do this.


You should probably change the ownership and permissions of /usr/local

back to your user account.

  sudo chown -R $(whoami):admin /usr/local

I tried to troubleshoot this using the command above and the multiple
suggestions provided here
<https://stackoverflow.com/questions/14527521/brew-doctor-says-warning-usr-local-include-isnt-writable>,
to no avail. Either the command didn't actually fix the problem or I didn't
have "permission" to make the change. Is there a way to install mrbayes
without Homebrew?

Thank you again for your help,

Rachael

**Comment by andkaha** [comment]
This sounds like an issue with your Homebrew installation in general. It may be a very old Homebrew version? I'm running Homebrew on Catalina without any issues whatsoever.  I have

```
[desktop] % brew --version
Homebrew 2.2.2-54-g8294060
Homebrew/homebrew-core (git revision 49e52; last commit 2020-01-07)
Homebrew/homebrew-cask (git revision bb0791; last commit 2020-01-07)
```

If I were you, I would possibly look into re-installing Homebrew from scratch.  Building MrBayes from sources is definitely possible on macOS, but it may require installing a few developer tools (and the Beagle library, if you want that, which would need compiling separately).  If your Homebrew installation doesn't want to play nicely, trying to build MrBayes from sources may end up becoming quite a large project.

**Comment by rmwade** [comment]
Yes, you were correct that I was using a very old version. The uninstall
and reinstall worked beautifully (I'm embarrassed I didn't think of it
sooner!).

Thank you again for all your help! MrBayes is now installed!

Best,

Rachael

**Comment by nylander** [comment]
Closing

**Comment by yudhiratna** [comment]
I failed to install mrbayes on Mac OS big sur M1 chip. Could anyone help me please, to solve the problem. thank you.

==> Installing mrbayes from brewsci/bio
Error: beagle: no bottle available!
You can try to install from source with:
  brew install --build-from-source beagle
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.

brew install --build-from-source beagle
==> Downloading https://github.com/beagle-dev/beagle-lib/archive/v3.1.2.tar.gz
Already downloaded: /Users/yudhiratnanugraheni/Library/Caches/Homebrew/downloads/15c4619d743d3ff1013dea23aafc2d821f0565217f17f5eddc12aac4dd438a74--beagle-lib-3.1.2.tar.gz
==> ./autogen.sh
==> ./configure --prefix=/opt/homebrew/Cellar/beagle/3.1.2_1 --without-cuda --di
==> make install
Last 15 lines from /Users/yudhiratnanugraheni/Library/Logs/Homebrew/beagle/03.make:
/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/mmintrin.h:394:19: error: use of undeclared identifier '__builtin_ia32_paddd'; did you mean '__builtin_arm_addg'?
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
                  ^
/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/mmintrin.h:352:19: note: '__builtin_arm_addg' declared here
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
                  ^
/Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/mmintrin.h:394:19: error: first argument of MTE builtin function must be a pointer ('__v2si' (vector of 2 'int' values) invalid)
    return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
                  ^                    ~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [libhmsbeagle_cpu_sse_la-BeagleCPUSSEPlugin.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!
