### ISSUE TITLE
Feature request: report PP:s for root partition in rooted trees

### ISSUE THREAD

**Issue by nylander** [NBISweden/MrBayes#149]
From user:

"For the next update of MrBayes, could you consider outputting support values (posterior probability) for the root-bipartition in rooted trees produced by non-stationary models. In most cases the standard outputs are unrooted tree, which does not have a root-node, so there is no question of a support value. 

For the datasets I have analyzed, the root bipartition is the same in all trees (after burnin), so I can manually assign a PP of 1.0. The root position was invariant even in cases where there was some topological uncertainty, the uncertainty was mostly among bipartitions closer to the tips."

**Comment by ronquist** [comment]
This should actually work in the new code in the feature/Seraina branch. I ran a test dataset and the two partitions closest to the root have support values 73% and 74%, which is clearly displayed in the sumt consensus tree. There is no partition below the two basal partitions in a rooted tree. If you still think there is a problem, please provide info so that we can replicate the behavior.

**Comment by ronquist** [comment]
The new code is now incorporated in the develop branch. I will close this issue now. Please repost if you think there is a remaining issue.
