### ISSUE TITLE
no topological change with uninformative data

### ISSUE THREAD

**Issue by marciopie** [NBISweden/MrBayes#185]
I am running  MrBayes (3.2.7a x86_64 on a MacBook Pro) with only one uninformative character (?) and the topologies won't change regardless of chain length. If I run the same code in an earlier version, it works fine.

The command block is:

begin MRBAYES; 
unlink shape=(all) tratio=(all) statefreq=(all) revmat=(all) pinvar=(all);
set usebeagle=no Beaglesse=no; 
rset brlenspr=clock:birthdeath; 
prset Extinctionpr = Fixed(0); 
prset Speciationpr=exponential(1); 
prset clockvarpr=ibr; 
prset ibrvarpr=exponential(10); 
mcmcp nruns=1 nchains=1 ngen=50000000 samplefreq=1000; 
end;

**Comment by zhangchicool** [comment]
The birth-death model implemented in 3.2.7 doesn't support mu=0 (pure birth) but the prior setting fails to check this. 
> prset Extinctionpr = Fixed(0);

Extinctionpr is restricted to be in (0, 1) to fix this issue for now.

Before 3.2.7, the birth-death probability distribution was conditioned on the number of extant tips, and seemed to allow extinction rate to be zero. But since 3.2.7, all b-d models have been changed to consistently condition on the root age, and the calculation has a log(extinction rate), which would result in -inf if extinction rate was zero.
