### ISSUE TITLE
FAST_LOG

### ISSUE THREAD

**Issue by kusalananda** [NBISweden/MrBayes#25]
The `FAST_LOG` macro used to be settable through `configure --enable-fastlog` (or similar), but is currently disabled unconditionally.

Do we want to add `--enable-fastlog` back into `configure`?

What does it actually do?

**Comment by ronquist** [comment]
It uses a look-up instead of actually calculating logs in computing likelihoods. I have not used it for a long time, after checking that the time gain was minimal. If you like, you can see if the code still works and if it gives some gain in computational speed (see quick-start tutorial in the manual for a one-page instruction on how to run a standard analysis).

If you want to spend some time cutting down computational time, then the scaling and the data parallelization (issues #19 and #21) are much more important. There is also very good potential in downsampling of site model mixtures, but it is more complicated to program (although there is a good start in the gibbsGamma code). There is some potential math conflicts between downsampling and the MCMCMC procedure and the estimation of model likelihoods. One also needs to switch between downsampling model components (when sampling substitution model parameters) and summarizing out components (when sampling over tree space) to not slow down convergence so much that one loses more time than one gains.

**Comment by kusalananda** [comment]
`FAST_LOG` code will be removed.
