### ISSUE TITLE
Average standard deviation of split frequencies

### ISSUE THREAD

**Issue by biozhajie** [NBISweden/MrBayes#30]
Hi Professor,

When I was using mrbayes, I have something confusion and have 4 questions:
1.  As the two runs converge onto the stationary distribution, we expect the average standard deviation of split frequencies to approach zero, reflecting the fact that the two tree samples become increasingly similar. But my questions is if nruns>2(say, 3), whether the average standard deviation is presented as a total value reflecting the similarities among the three tree samples or presented as paired values reflecting the similarity of each pair tree samples among the 3?
2. After a huge numbers of MCMC steps, it can be seen the average standard deviation of split frequencies indeed approach zero while the MCMC run.  However, in a short run,  it seems the change of the average standard deviation is not a continuous process, because I found the values always change among  a limited number of discrete values, please see the example below. Please tell me why? 

```
     13370000 -- [-47404.821] (-48001.334) (-47558.021) (-47754.843) * (-48142.756) (-47589.919) [-47437.287] (-47768.668) .. -- 1312:35:43

      Average standard deviation of split frequencies: 0.013077


      Average standard deviation of split frequencies: 0.013099

      13350000 -- [-47407.277] (-47991.074) (-47636.842) (-47701.000) * (-48105.463) (-47519.740) [-47416.206] (-47772.493) .. -- 1315:18:14

      Average standard deviation of split frequencies: 0.013099

      13360000 -- [-47399.334] (-47904.829) (-47615.648) (-47753.082) * (-48089.281) (-47605.298) [-47457.465] (-47766.188) .. -- 1313:57:47

      Average standard deviation of split frequencies: 0.013094

      13370000 -- [-47404.821] (-48001.334) (-47558.021) (-47754.843) * (-48142.756) (-47589.919) [-47437.287] (-47768.668) .. -- 1312:42:15

      Average standard deviation of split frequencies: 0.013077

      13350000 -- [-47407.277] (-47991.074) (-47636.842) (-47701.000) * (-48105.463) (-47519.740) [-47416.206] (-47772.493) .. -- 1315:27:56

      Average standard deviation of split frequencies: 0.013099

      13330000 -- [-47416.756] (-47985.223) (-47643.199) (-47761.140) * (-48088.912) (-47606.148) [-47467.146] (-47765.563) .. -- 1318:11:36

      Average standard deviation of split frequencies: 0.013099

      13350000 -- [-47407.277] (-47991.074) (-47636.842) (-47701.000) * (-48105.463) (-47519.740) [-47416.206] (-47772.493) .. -- 1315:32:09

      Average standard deviation of split frequencies: 0.013099

      13360000 -- [-47399.334] (-47904.829) (-47615.648) (-47753.082) * (-48089.281) (-47605.298) [-47457.465] (-47766.188) .. -- 1314:12:03

      Average standard deviation of split frequencies: 0.013094


      Average standard deviation of split frequencies: 0.013099
```
1. Why in some step of MCMC there are multiple entries of average standard deviation of split frequencies but in other step there is only one entries? Please see example as below:

```
13350000 -- [-47407.277] (-47991.074) (-47636.842) (-47701.000) * (-48105.463) (-47519.740) [-47416.206] (-47772.493) .. -- 1314:47:30

      Average standard deviation of split frequencies: 0.013099


      Average standard deviation of split frequencies: 0.013099


      Average standard deviation of split frequencies: 0.013087


      Average standard deviation of split frequencies: 0.013094


      Average standard deviation of split frequencies: 0.013087


      Average standard deviation of split frequencies: 0.013094


      Average standard deviation of split frequencies: 0.013087


      Average standard deviation of split frequencies: 0.013099

      13330000 -- [-47416.756] (-47985.223) (-47643.199) (-47761.140) * (-48088.912) (-47606.148) [-47467.146] (-47765.563) .. -- 1317:50:45

      Average standard deviation of split frequencies: 0.013099


      Average standard deviation of split frequencies: 0.013094


      Average standard deviation of split frequencies: 0.013099

      13370000 -- [-47404.821] (-48001.334) (-47558.021) (-47754.843) * (-48142.756) (-47589.919) [-47437.287] (-47768.668) .. -- 1312:35:43

      Average standard deviation of split frequencies: 0.013077


      Average standard deviation of split frequencies: 0.013099

      13350000 -- [-47407.277] (-47991.074) (-47636.842) (-47701.000) * (-48105.463) (-47519.740) [-47416.206] (-47772.493) .. -- 1315:18:14

      Average standard deviation of split frequencies: 0.013099

      13360000 -- [-47399.334] (-47904.829) (-47615.648) (-47753.082) * (-48089.281) (-47605.298) [-47457.465] (-47766.188) .. -- 1313:57:47

      Average standard deviation of split frequencies: 0.013094

      13370000 -- [-47404.821] (-48001.334) (-47558.021) (-47754.843) * (-48142.756) (-47589.919) [-47437.287] (-47768.668) .. -- 1312:42:15
```
1.  Why the step went back? please see example in question 2 and 3.

By the way,  my running sets are nruns=3 and nchains=4, and the MCMC was implemented under a parallel environment.

Thanks,

Jie

**Comment by winni2k** [comment]
Hi @biozhajie,
There is now a clarification of the definition of ASDSF in https://github.com/NBISweden/MrBayes/issues/191. From the definition I can derive that the answer to your first question must be that all three chains are compared together.

Regarding your question 2., I would expect ASDSF to vary because MCMC chains vary stochastically (randomly). How close two chains are to each other will always vary. At the beginning of the run that variance should be larger than later in the run.

**Comment by ronquist** [comment]
Hi @biozhajie !

Indeed, the answer to your first question is, as pointed out by @winni2k , that the default value is for all chains compared. With sumt, you can also compute the pairwise values after your run has completed, if you are interested in those.

Regarding question 2, the ASDSF values can appear discrete because we are computing them over a finite number of trees in the samples. This effect will depend on the size of the trees and the tree samples.

The third question appears to be a bug. The number of printed ASDSF values should be constant between the printed log likelihoods. If you can repeat this behavior with a sample dataset and fixed run settings, please file a new issue and share the files causing the problems and info about the version of the program you are running, and we will look at it.

I will close this issue now!

/Fredrik
