### ISSUE TITLE
Compiler warnings gcc 7.2.0

### ISSUE THREAD

**Issue by nylander** [NBISweden/MrBayes#64]
Compiling on Linux (gcc (Ubuntu 7.2.0-8ubuntu3.2) 7.2.0) gives me a lot of Warnings. Mostly from `-Wmaybe-uninitialized`, `-Wunused-but-set-variable`, but also `-Wformat-overflow=`, and `-Wstrict-overflow`. These should be corrected.

**Comment by kusalananda** [comment]
Commit 98fc4a3  fixes this by initializing some arrays to zero (NULL pointers, really), and increasing the buffer sizes used for output filenames.

There is a single warning that I can't get rid of:

> utils.c: In function ‘ElTran’:
> cc1: warning: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Wstrict-overflow]

Since this does not really say what piece of code it's referring to, I find it hard to spot the cause of the warning.
